config/routes.rb
BookmarkSite::Application.routes.draw do

  match 'usernotfound' => 'static_pages#usernotfound', as: 'usernotfound'

  resources :sessions, :only => [:create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => "static_pages#welcome"

  get "jsfiles/bookmarklet(.:format)" => "jsfiles#bookmarklet", :as => :bookmarklet
  get "jsfiles/jquery_bookmarklet.min(.:format)" => "jsfiles#jquery_bookmarklet", :as => :bookmarklet_setup
  get "jsfiles/cleanslate(.:format)" => "jsfiles#cleanslate", :as => :cleanslate
  get "jsfiles/playground(.:format)" => "jsfiles#playground", :as => :playground
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#process_bookmarklet', :via => :post
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#preflight', :via => :options

  match 'playlists/:playlist_id/user_bookmarks/:id/move(.:format)' => 'user_bookmarks#move', :via => :post

  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'info', to: 'static_pages#info', as: 'info'
  get 'privacy', to: 'static_pages#privacy', as: 'privacy'
  get 'contact', to: 'static_pages#contact', as: 'contact'

  resources :playlists do
    resources :user_bookmarks
  end

  resources :bookmark_urls, :only => [:create]

  match 'users/temp(.:format)' => 'users#temp', :as => :temp_users, :via => :get
  match 'users/create_temp(.:format)' => 'users#create_temp', :as => :create_temp_users, :via => :get

  resources :users do
    member do
      get 'upgrade'
      put 'process_upgrade'
    end
  end

  match '/:username' => 'users#show'

end

app/views/static_pages/info.html.erb
<div class="row-fluid">
	<div class="span4 offset1" id="signup-container">
		<a id="signing-up"></a><h2>Signing Up</h2>
		<div class="row-fluid">
			<div class="span12">
				<h4>What it lets you do:</h4>
				<p>Having an account lets you<p>
				<ul>
					<li>keep your bookmarks and playlists saved for good after you've left the site</li>
					<li>access them easily by going to <i>vrepo.com/YourUsername</i></li>
					<li>use the bookmarklet to bookmark pages when you're on other sites.</li>
					<li>edit your account by change your username and password.</a>
				</ul>
				<p>So you can still <i>try out</i> the site without actually joining, but there's less you can do, and joining is really easy!</p>
			</div>
		</div>
		<hr>
		<div class="row-fluid">
			<div class="span12">
				<h4>As simple as proving you're a human</h4>
				<p>Just by playing through a PlayThru™ game, we can filter out bots and give you a profile. After that, you can give edit your profile to give yourself a username and password if you want.</p>
				<p>One thing: for this site to work, you do need cookies and javascript enabled, and it works best in up-to-date versions of Chrome, Firefox, Safari, and IE 7+. </p>
				<div class="center-button-table"><div class="center-button-cell">
					<% if current_user%>
			  		<% if current_user.human? %>
			  			<%= link_to "Edit Account »", edit_user_path(current_user), :class=>"btn btn-cherry " %>
				  	<% else %>
			  			<%= link_to "Sign Up »", edit_user_path(current_user), :class=>"btn btn-cherry " %>
				  	<% end %>
			  	<% else %>
		  			<%= link_to "Sign Up »", new_user_path, :class=>"btn btn-cherry signup-modal-link" %>
			  	<% end %>
			  </div></div>
			</div>
		</div>
		<hr>
		<div class="row-fluid">
			<div class="span12">
				<h4>Your Privacy</h4>
				<p>I'm <strong>not asking for your email address.</strong> If I ever do want it then I'll ask ya'll nicely, and it'll be entirely optional. I don't collect/share any kind of personal data. Here is a link to the site's privacy policy, and here's a link to frequently asked questions. I take your privacy seriously: I realize that's kind of the entire point of using this.</p>
			</div>
		</div>
	</div>

	<div class="span4 offset2" id="add-links-container">
		<a id="adding-links"></a><h2>Adding Links</h2>
		<div class="row-fluid">
			<div class="span12">
				<h4>Bookmarklet</h4>
				<p class="contains_bookmarklet">To use it, drag this <a id="bookmarklet" href ="javascript:(function(){jq=document.createElement('SCRIPT');jq.type='text/javascript';jq.src='//www.vrepo.com/jsfiles/jquery_bookmarklet.min.js';document.getElementsByTagName('head')[0].appendChild(jq);})();"><%= image_tag 'bookmarklet.png' %></a> and drop it in your bookmark bar, which should be under your address bar.</a></p>
				<br />
				<p>When you're logged in here and click it, and something like this image below will show up near the top of your website.</p><br />
				<%= image_tag 'Bookmarklet Example.png' %><br /><br />
				<p>Keep in mind that this only works if you have an account and are logged in.</p>
			</div>
		</div>
		<hr>
		<div class="row-fluid">
			<div class="span12">
				<h4>Form</h4>
				<p>Click the button below (there'll be a button like this on your standard home page), and a modal window will come up and let you set the title and submit the link.</p>
			 	<p>From there, it'll take you to the page containing your links.</p>
			 	<div class="center-button-table"><div class="center-button-cell">
			 		<% if current_user %>
			  		<%= link_to "Try it Out <i class='icon-plus icon-white'></i>".html_safe, user_path(current_user),class:"btn btn-primary"%><br />
		  		<% else %>
			  		<a href="#" class="btn btn-primary disabled">Add A Link <i class="icon-plus icon-white"></i></a><br />
		  		<% end %>
			  </div></div>
			</div>
		</div>
		<hr>
		<div class="row-fluid">
			<div class="span12">
				<h4>Drag-and-Drop</h4>
				<p>Just drag a the URL off the address bar from another site and drop it onto any page with an "Add Bookmark" button like the one above or below this, (including this page), if you want to try it now like this:</p>
				<%= image_tag 'dragondrop.png' %><br />
			 	<p>A modal window will come up and let you set the title and submit the link.</p>
			</div>
		</div>
	</div></div>

app/views/static_pages/welcome.html.erb
<div class="row-fluid">
	<div class="span12">
		<div class="hero-unit home">
		  <h1>Welcome to VRepo!</h1>
		  <h3>A Utility for Anonymously Bookmarking Adult Content</h3>
		  <br/>
			<div class="row-fluid options">
			  <div class="span3">
			  	<div class="center-button-table"><div class="center-button-cell">
		  		<% if current_user%>
		  			<%= link_to "Edit Account »", '#', :class=>"btn btn-cherry btn-large signup-modal-link" %>
		  			<div id="signup-modal-holder">
			  			<%= render '/users/modal_edit' %>
			  		</div>
			  	<% else %>
		  			<%= link_to "Sign Up »", '#', :class=>"btn btn-cherry btn-large signup-modal-link" %>
		  			<!-- Something that triggers login-->
		  			<div id="signup-modal-holder">
			  			<%= render '/users/modal_new' %>
			  		</div>
			  	<% end %>
		  		<br />
		  		<a href="#" id="signing-anchor-link" data-toggle="tooltip" title="This button brings up a form to verify you're human." data-placement="bottom" style="font-size: 14px; font-weight:500;line-height:14px;">More Information.</a>
			  	</div></div>
			  </div>
			  <div class="span3">
			  	<div class="center-button-table"><div class="center-button-cell">
		  			<%= link_to "Log In »", login_path, :class=>"btn btn-warning btn-large" %>
		  		<br />
		  		<a href="#" id="signing-anchor-link" data-toggle="tooltip" title="If you're logged out, you can also login by clicking the top-right dropdown menu." data-placement="bottom" style="font-size: 14px; font-weight:500;line-height:14px;">For Returning Users.</a>
			  	</div></div>
			  </div>
			  <div class="span3">
			  	<div class="center-button-table"><div class="center-button-cell">
			  		<a href="/playlists/9" class="btn btn-success btn-large">Browse &raquo;</a><br />
			  		<a href="#" data-toggle="tooltip" title="This button will take you my playlist so can check out how one looks." data-placement="bottom" style="font-size: 14px; font-weight:500;line-height:14px;">More Information.</a>
			  	</div></div>
			  </div>
			  <div class="span3">
			  	<div class="center-button-table"><div class="center-button-cell">
			  		<% if current_user%>
				  		<a href="#" class="btn btn-primary btn-large new-bookmark-modal-link">Get Started <i class="icon-plus icon-white"></i></a><br />
			  			<div id="new-bookmark-modal-holder">
				  			<%= render '/user_bookmarks/modal_new' %>
				  		</div>
				  		<a href="#threeways" id="add-anchor-link" data-toggle="tooltip" title="Click this link to scroll to the part about adding boomkmarks." data-placement="bottom" style="font-size: 14px; font-weight:500;line-height:14px;">More Information.</a>
			  		<% else %>
				  		<a href="#" class="btn btn-primary btn-large disabled">Add A Link <i class="icon-plus icon-white"></i></a><br />
				  		<a href="/signup" id="add-anchor-link" data-toggle="tooltip" title="This button is disabled because you're not logged into any kind of account. Click this link to sign up." data-placement="bottom" style="font-size: 14px; font-weight:500;line-height:14px;">More Information.</a>
			  		<% end %>
			  	</div></div>
			  </div>
			</div>
		</div>
	</div>
</div>
<div class="row-fluid info2">
	<div class = "span8">
		<div class="row-fluid">
			<h3 id="threeways">Three Ways to Add Links</h3>
		  <div class="span4">
		    <div class="feature">
		    	<div>
					      <a href="#threeways" class="btn btn-block btn-primary">Bookmarklet</a>
					      <%= image_tag "bookmark.png" %>
				  </div>
		    </div>
		    <div class="more-info">
			    <p class="contains_bookmarklet">Drag this icon <a id="bookmarklet" href ="javascript:(function(){jq=document.createElement('SCRIPT');jq.type='text/javascript';jq.src='//www.vrepo.com/jsfiles/jquery_bookmarklet.min.js';document.getElementsByTagName('head')[0].appendChild(jq);})();"><%= image_tag 'bookmarklet.png' %></a> and drop it in your bookmark bar. Click it when you're on another site and a small form will show up</p><br />
					<%= image_tag 'Bookmarklet Example.png' %>
		  	</div>
		  </div>
		  <div class="span4">
		    <div class="feature"><div>
			      <a href="#threeways" class="btn btn-block btn-primary">Drag &amp; Drop</a>
			      <%= image_tag "blood-drop-icon.png" %>
					</div></div>
		    <div class="more-info">Drag the link to a video from any other site into the VRepo home (here), account main, or playlist page.<br />
		    <%= image_tag 'dragondrop.png' %></div>
		  </div>
		  <div class="span4">
		    <div class="feature">
		    	<div>
		      <a href="#threeways" class="btn btn-block btn-primary">Form</a>
		      <%= image_tag "form.png" %>
		    </div>
		    </div>
		    <div class="more-info">Click the standard "Add A Link" button to manually add your favorite links on a form. <br/> 
		    	<% if current_user%>
			  		<br /><br /><br /><br />
			  		<div style="margin-left:auto; margin-right:auto; width:60%">
				  		<a href="#" class="btn btn-primary btn-block new-bookmark-modal-link">Add A Link <i class="icon-plus icon-white"></i></a>
				  	</div>
		  		<% end %>
			  </div>
		  </div>
		</div>
	</div>

	<div class="span4">
		<h3>Info</h3>
		This site is intended as a <strong>safe</strong> place to
		<ul>
			<li><strong>Access</strong> - from <i>vrepo.com/YourUserName</i></li>
			<li><strong>Watch</strong> - videos from your playlists</li>
			<li><strong>Categorize</strong> - links and videos for easy viewing</li>
		</ul>
		your adult video links. 
		<br /><br />
		<p> VRepo.com does not and has no intention of collecting your e-mail or any other information which can be traced back to your offline identity. <p>
	</div>
</div>
</div>