config/routes.rb
BookmarkSite::Application.routes.draw do

  match 'usernotfound' => 'static_pages#usernotfound', as: 'usernotfound'

  resources :sessions, :only => [:create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => "static_pages#welcome"

  get "jsfiles/bookmarklet(.:format)" => "jsfiles#bookmarklet", :as => :bookmarklet
  get "jsfiles/jquery_bookmarklet.min(.:format)" => "jsfiles#jquery_bookmarklet", :as => :bookmarklet_setup
  get "jsfiles/cleanslate(.:format)" => "jsfiles#cleanslate", :as => :cleanslate
  get "jsfiles/playground(.:format)" => "jsfiles#playground", :as => :playground
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#process_bookmarklet', :via => :post
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#preflight', :via => :options

  match 'playlists/:playlist_id/user_bookmarks/:id/move(.:format)' => 'user_bookmarks#move', :via => :post

  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'info', to: 'static_pages#info', as: 'info'
  get 'privacy', to: 'static_pages#privacy', as: 'privacy'
  get 'contact', to: 'static_pages#contact', as: 'contact'

  resources :playlists do
    resources :user_bookmarks
  end

  resources :bookmark_urls, :only => [:create]

  match 'users/temp(.:format)' => 'users#temp', :as => :temp_users, :via => :get
  match 'users/create_temp(.:format)' => 'users#create_temp', :as => :create_temp_users, :via => :get

  resources :users do
    member do
      get 'upgrade'
      put 'process_upgrade'
    end
  end

  match '/:username' => 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'bcrypt'
  
  attr_accessible :username, :regularized_username, :password, :access, :bookmarklet_user_key
  #check if proved-human needs to be accessible
  #has_secure_password :validations => false
  has_one :default_list, :class_name => 'Playlist'
  has_many :playlists, :class_name => 'Playlist'
  before_save :create_remember_token, :reset_bookmarklet_user_key
  before_validation :create_regularized_username
  attr_accessor :password

  validates_presence_of :password_digest, :unless => "password.blank?"
  #validates_confirmation_of :password, :if => :human?
  validates_uniqueness_of :regularized_username, :message => " has already been registered"
  validate :username_is_not_a_route
  # validates_format_of :username
  # validate :password, :length => {:in => 3..30}
  
  #-- from secure_password.rb --
  if respond_to?(:attributes_protected_by_default)
    def self.attributes_protected_by_default
      super + ['password_digest']
    end
  end


  def authenticate(unencrypted_password)
    if BCrypt::Password.new(password_digest) == unencrypted_password
      self
    else
      false
    end
  end

  # Encrypts the password into the password_digest attribute.
  def password=(unencrypted_password)
    @password = unencrypted_password
    unless unencrypted_password.blank?
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end
  
  #--- done with things from secure_password.rb
  def purge_self
    if !(self.human?) and self.default_list.user_bookmarks.empty? and self.playlists.count == 1 and self.updated_at == self.created_at
      self.default_list.destroy
      self.destroy
    end
  end

  def lists
    self.playlists - [self.default_list]
  end

  def reset_bookmarklet_user_key
    self.bookmarklet_user_key = SecureRandom.urlsafe_base64
  end

  def human?
    self.human
  end
  
  protected
    def username_is_not_a_route
      path = Rails.application.routes.recognize_path("/#{regularized_username}" ) rescue nil
      if path && !path[:username]
        errors.add(:username, ": \"#{username}\" conflicts with the site's routing") 
      else
        path = Rails.application.routes.recognize_path("/#{username}") rescue nil
        if path && !path[:username]
          errors.add(:username, ": \"#{username}\" conflicts with the site's routing") 
        end
      end
    end

    def create_regularized_username
      self.regularized_username = self.username.gsub(/\s/,'').downcase
    end

  private

  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64 if self.remember_token.blank?
  	end

  	def logged_in?
  		session[:remember_token]  == self.remember_token
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :logged_in, :except => [:new, :create, :show]
	before_filter :authorize, :only => [:edit, :update]
	before_filter :authorize_or_accessible, :only => [:show]
	before_filter :authorize_admin, :only => [:index]

	def new
		if flash[:user]
			@user = flash[:user]
		else
			@user = User.new
		end
		# ayah = AYAH::Integration.new('bd04599eed9a3768e786ecbf73defecc313a59b1', '08dc9c32c3d7426be6aebb66b7cff9958b4d9c27')
		# @publisher_html = ayah.get_publisher_html
		if request.xhr?
			render :partial => 'modal_new'
		else
			render 'new'
		end
	end

	def create
		@user = User.new(params[:user])
		session_secret = params['session_secret'] # in this case, using Rails
		# ayah = AYAH::Integration.new('bd04599eed9a3768e786ecbf73defecc313a59b1', '08dc9c32c3d7426be6aebb66b7cff9958b4d9c27')
		# ayah_passed = ayah.score_result(session_secret, request.remote_ip)
		# if ayah_passed
			@user.admin = false
			@user.human = true
			if(@user.save)
				session[:remember_token] = @user.remember_token
				@user.default_list = Playlist.create(:playlist_name => "default list")
				respond_to do |format|
					format.html { redirect_to user_path(@user), :notice => "You've signed up successfully." }
					format.json { render :json => {"success" => "true" } }
				end
			else
				respond_to do |format|
					format.html { 
						flash[:user] = @user
						redirect_to signup_path
					}
					format.json { render :json =>{ "errors" => @user.errors.full_messages }}
				end
			end
		# else
			# respond_to do |format|
			# 	format.html { render 'new', :notice => "You didn't successfully prove you're human." }
			# 	format.json { render :json =>{ "errors" => ["You didn't successfully prove you're human."] } }
			# end
		# end
	end

	# def upgrade
	# 	if current_user.nil?
	# 		render :partial => 'error' #message about how they need cookies enabled
	# 	else
	# 		@user = current_user
	# 		ayah = AYAH::Integration.new('bd04599eed9a3768e786ecbf73defecc313a59b1', '08dc9c32c3d7426be6aebb66b7cff9958b4d9c27')
	# 		@publisher_html = ayah.get_publisher_html
	# 		render :partial => 'modal_upgrade'
	# 		# if @user.human?
	# 		# 	render :partial => 'edit'
	# 		# else
	# 		# 	render :partial => 'modal_new'
	# 		# end
	# 	end
	# end

	def update
		@user = User.find(params[:id])
		# if !(@user.human)
		# 	session_secret = params['session_secret'] # in this case, using Rails
		# 	ayah = AYAH::Integration.new('bd04599eed9a3768e786ecbf73defecc313a59b1', '08dc9c32c3d7426be6aebb66b7cff9958b4d9c27')
		# 	ayah_passed = ayah.score_result(session_secret, request.remote_ip)
		# end
		# if @user.human or ayah_passed
			@user.update_attributes(params[:user])
			if(!params[:user][:password].blank?)
				@user.password = params[:user][:password]
			end
			if(!params[:user][:username].blank?)
				@user.username = params[:user][:username]
			end
			# @user.human = true
			if(@user.save)
				respond_to do |format|
					format.html { redirect_to user_path(@user), :notice => "You've signed up successfully." }
					format.json { render :json => {"success" => "true" } }
				end
			else
				respond_to do |format|
					# format.html { render edit_user_path(@user), :notice => "You had some errors with your changes." }
					# @user = User.find(params[])
					format.html { 
						flash[:user] = @user
						redirect_to edit_user_path(@user)
					}
					format.json { render :json =>{ "errors" => @user.errors.full_messages }}
				end
			end
		# else
		# 	respond_to do |format|
		# 		format.html { render 'edit', :notice => "You didn't successfully prove you're human." }
		# 		format.json { render :json =>{ "errors" => ["You didn't successfully prove you're human."] } }
		# 	end
		# end
	end

	def edit
		if(flash[:user])
			@user = flash[:user]
		else
			@user = User.find(params[:id])
		end
		# if(!@user.human)
		# 	ayah = AYAH::Integration.new('bd04599eed9a3768e786ecbf73defecc313a59b1', '08dc9c32c3d7426be6aebb66b7cff9958b4d9c27')
		# 	@publisher_html = ayah.get_publisher_html
		# end
		if request.xhr?
			render :partial => 'modal_edit'
		else
			render 'edit'
		end
	end

	# def update
	# 	@user = User.find(params[:id])
	# 	@user.update_attributes(params[:user])
	# 	if(@user.save)
	# 		redirect_to users_path(@user), :notice => "You've signed up successfully."
	# 	else
	# 		render 'edit'
	# 	end
	# end

	def show
		# if(params[:id])
		# 	@user = User.find(params[:id])
		# else
		# 	@user = User.find_by_regularized_username(params[:username].gsub(/\s/,'').downcase)
		# 	# logger.ap @user
		# 	if @user.nil?
		# 		# logger.ap 'dammit'
		# 		redirect_to usernotfound_path
		# 	end
		# end
		# if @user
			logger.ap session
			@playlist = @user.default_list
			@lists = @user.lists
			# for modal new bookmark
			@user_bookmark = @playlist.user_bookmarks.build
			@bookmark_url = BookmarkUrl.new
		# end
	end

	def index
		@users = User.all
	end

	private
		def logged_in
			if(current_user.nil?)
				redirect_to login_path, :notice => "You have to log in to do that."
			end
		end

		def authorize
			redirect_to login_path, :notice => "You have to log in as that user to do that." unless ((current_user.id.to_s == params[:id]) or current_user.admin)
		end
		
		def authorize_or_accessible
			if params[:id]
				@user = User.find(params[:id])
			elsif params[:username]
				@user = User.find_by_regularized_username(params[:username].gsub(/\s/,'').downcase)
			end
			if @user
				if !@user.access
					if current_user
						if !((current_user.id.to_s == params[:id]) or current_user.admin)
							redirect_to login_path, :notice => "You have to log in as that user to do that." unless ((current_user.id.to_s == params[:id]) or current_user.admin or @user.access)
						end
					else
						redirect_to login_path, :notice => "You have to log in as that user to do that." unless ((current_user.id.to_s == params[:id]) or current_user.admin or @user.access)
					end
				end
			else
				redirect_to usernotfound_path
			end
		end

		def authorize_admin
			redirect_to login_path, :notice => "You have to be an admin access that." unless (current_user.admin)
		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/_modal_edit.html.erb
<div class="modal hide fade signup-modal" tabindex="-1">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h2>Edit Account: <%= @user.username %></h2>
  </div>
  <%= form_for @user, :html => { "data-type" => "json"}, :remote=>true do |f|%>
    <div class="modal-body">
      <%= f.text_field :username, :value=> "",:placeholder=>"Set A New Username" %><br />
      <%= f.password_field :password, :placeholder=>"Set a New Password" %><br>
      <%# if !(@user.human?) %>
        <%#= @publisher_html.try(:html_safe)  %>
      <%# end %>
    </div>
    <div class="modal-footer">
      <div class = "form-buttons">
        <button type="submit" class="btn btn-primary">Create Account</button>
        <button class="btn" data-dismiss="modal">Close</button>
        <!-- <button class="btn" data-dismiss="modal">Add Another</button> -->
      </div>
      <div class = "alert-container-success">
        <div class = "alert alert-success">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          Your account was successfully created. Your bookmarks will be <%= link_to 'here', @user %>.
        </div>
      </div>
      <div class = "alert-container-error">
        <div class = "alert alert-error alert-block">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          You had the following errors:
          <!-- errors -->
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_modal_new.html.erb
<div class="modal hide fade signup-modal" tabindex="-1">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h2>Sign Up!</h2>
  </div>
  <%= form_for @user, :html => { "data-type" => "json"}, :remote=>true do |f|%>
    <div class="modal-body">
      <%= f.text_field :username, :placeholder=>"Username" %><br />
      <%= f.password_field :password, :placeholder=>"Password" %><br />
      <%#= @publisher_html.try(:html_safe)  %>
    </div>
    <div class="modal-footer">
      <div class = "form-buttons">
        <button type="submit" class="btn btn-primary">Create Account</button>
        <button class="btn" data-dismiss="modal">Close</button>
        <!-- <button class="btn" data-dismiss="modal">Add Another</button> -->
      </div>
      <div class = "alert-container-success">
        <div class = "alert alert-success">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          Your account was successfully created. Your bookmarks will be <%= link_to 'here', @user %>.
        </div>
      </div>
      <div class = "alert-container-error">
        <div class = "alert alert-error alert-block">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          You had the following errors:
          <!-- errors -->
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row-fluid">
  <div class="span4 offset2">
<h2>Edit Account: <%= current_user.username %></h2><br />
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <!-- <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <%# @user.errors.full_messages.each do |message| %>
          <li><%#= message %></li>
        <%# end %>
      </ul>
    </div> -->
    <% @user.errors.full_messages.each do |msg| %>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg%>
        </div>
    <% end %>
  <% end %>
  <%= f.text_field :username, :value=> "", :placeholder=>"Set A New Username"%><br /><br />
  <%= f.password_field :password, :placeholder=>"Set A New Password" %><br /><br />
  <label class="checkbox">
    <%= f.check_box :access %>
    Check this box if you want to be able to access <i>www.vrepo.com/<%=@user.username%></i> without having to log in.
  </label><br /><br />
  <%# if !@user.human %>
    <!-- <p>Confirm you're human for the form go through and save your account.</p> -->
    <%#= @publisher_html.html_safe %><br />
  <%# end %>
  <button type="submit" class="btn btn-primary btn-large">Submit Changes</button>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="row-fluid"><ul>
	<% @users.each do |user| %>
		<li><%= link_to (user.username.nil?) ? user_path(user) : user.username, user %></li>
	<% end %>
</ul></div>

app/views/users/new.html.erb
<div class="row-fluid">
  <div class="span4 offset2">
<h1>Sign Up!</h1>
<br/>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg%>
        </div>
    <% end %>
  <% end %>
  <%= f.text_field :username, :placeholder=>"Username"%><br /><br />
  <%= f.password_field :password, :placeholder=>"Password" %><br /><br />
  <%#= @publisher_html.html_safe %><br />
  <button type="submit" class="btn btn-primary btn-large">Create Account</button>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<%= render '/layouts/info_pane' %>
<div class="row-fluid">
<%= render '/layouts/sidebar' %>
<div class="span5" id="bookmark_list_view">
  <% if @user != current_user %>
     <h3><%= @user.username %>'s</h3>
   <% end %>
  <h3>Unsorted Bookmarks</h3>
  <% if current_user %>
    <% if @playlist.user == current_user %>
      <%= link_to 'Add A Link <i class="icon-plus icon-white"></i>'.html_safe, '', class:"btn btn-primary new-bookmark-modal-link", "data-toggle"=>"tooltip", "data-trigger"=>"manual", "data-title"=>"here", "data-placement"=>"right" %>
      <div id="new-bookmark-modal-holder">
          <%= render '/user_bookmarks/modal_new' %>
      </div>
    <% end %>
  <% end %>
  <br />
  <div class="input-prepend">
    <span class="add-on"><i class="icon-filter"></i></span>
    <%= search_field_tag 'filter_uncategorized', '', :placeholder=>"Filter Bookmarks" , "data-toggle"=>"tooltip", "data-trigger"=>"manual", "data-title"=>"here", "data-placement"=>"bottom"%>
  </div>
  <div class="bookmark-list">
    <% @playlist.user_bookmarks.reverse.each_with_index do |user_bookmark,i| %>

      <% if i > 0 and !user_bookmark.id.nil? %>
        <hr>
      <% end %>
      
      <% if user_bookmark.id %>
        <%= render :partial =>'/user_bookmarks/bookmark_fields.html.erb', :locals => {:user_bookmark => user_bookmark} %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="span4">
  <div id="detail_bookmark_view_container">
    <div id="detail_bookmark_view">
    </div>
  </div>
</div>
</div>

app/views/users/temp.html.erb
<div class="row-fluid">
	<% unless @user.nil? %>
	<% if @user.errors.any? %>
	  <div class="error_messages">
	    <h2>Form is invalid</h2>
	    <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	    </ul>
	  </div>
	<% end %>
<% end %>

<h1>save your changes</h1>

<p>you can save your changes without making an actual account. we do have to use a cookie for that but of course it doesn't store anything personal and we won't share it so anybody so that someone could use it to track you. it's just a random sequence of letters and numbers. </p>

<p>just finish the task below to prove you're a human. then, as long as you don't clear your cookies, you'll be able to add and access your changes on this computer. later, if you want, you can make yourself a username and password so you can access and add links anywhere, as well as log in and out, (and maybe more if we figure out more stuff for users to be able to do) </p>

<h3>Task:</h3>
<%= link_to 'Click Me', create_temp_users_path, :id => 'create_temp_link' %><!-- 
<%= link_to 'Click Me', create_temp_users_path, :method => :post, :remote => true, :id => 'create_temp_link' %> -->
</div>