config/routes.rb
BookmarkSite::Application.routes.draw do

  match 'usernotfound' => 'static_pages#usernotfound', as: 'usernotfound'

  resources :sessions, :only => [:create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => "static_pages#welcome"

  get "jsfiles/bookmarklet(.:format)" => "jsfiles#bookmarklet", :as => :bookmarklet
  get "jsfiles/jquery_bookmarklet.min(.:format)" => "jsfiles#jquery_bookmarklet", :as => :bookmarklet_setup
  get "jsfiles/cleanslate(.:format)" => "jsfiles#cleanslate", :as => :cleanslate
  get "jsfiles/playground(.:format)" => "jsfiles#playground", :as => :playground
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#process_bookmarklet', :via => :post
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#preflight', :via => :options

  match 'playlists/:playlist_id/user_bookmarks/:id/move(.:format)' => 'user_bookmarks#move', :via => :post

  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'info', to: 'static_pages#info', as: 'info'
  get 'privacy', to: 'static_pages#privacy', as: 'privacy'
  get 'contact', to: 'static_pages#contact', as: 'contact'

  resources :playlists do
    resources :user_bookmarks
  end

  resources :bookmark_urls, :only => [:create]

  match 'users/temp(.:format)' => 'users#temp', :as => :temp_users, :via => :get
  match 'users/create_temp(.:format)' => 'users#create_temp', :as => :create_temp_users, :via => :get

  resources :users do
    member do
      get 'upgrade'
      put 'process_upgrade'
    end
  end

  match '/:username' => 'users#show'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :playlist_name, :public, :user_id, :user_bookmarks_attributes, :bookmark_urls_attributes
  has_many :user_bookmarks #, :dependent => :destroy
  has_many :bookmark_urls, :through => :user_bookmarks
  validates_existence_of :user
  validates :playlist_name, :length => {:in => 3..30}
  belongs_to :user
  accepts_nested_attributes_for :user_bookmarks, :allow_destroy => :true
  accepts_nested_attributes_for :bookmark_urls
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
	before_filter :authorize_owner, :only => [:edit, :update, :delete ]
	before_filter :authorize_show_playlist, :only => [:show]
	before_filter :authorize, :only => [:new, :create, :index]
	
	def new
		@playlist = current_user.playlists.build
	end

	def create
		@playlist = current_user.playlists.build(params[:playlist])
		if(@playlist.save)
			redirect_to @playlist, :notice => "Playlist Created Successfully."
		else
			render 'new'
		end
	end

	def show
		@playlist = Playlist.find(params[:id])
		if current_user
			@lists = current_user.lists
			@user_bookmark = UserBookmark.new
			@bookmark_url = BookmarkUrl.new 	#this is because i'm doing the 'new' form differently
		end
	end

	def edit
		@playlist = current_user.playlists.find(params[:id])
		@lists = current_user.lists
	end
	
	def update
		@playlist = current_user.playlists.find(params[:id])
		@playlist.update_attributes(params[:playlist])
		respond_to do |format|
			format.html {
		    if @playlist.save
		      redirect_to @playlist, notice: "Successfully updated playlist."
		    else
		      render 'edit'
		    end
		  }
		  format.js {
		  	render :nothing => true
		  }
		end
	end

	def index
		@lists = current_user.lists 
	end
	
	def destroy
		@playlist = current_user.lists.find(params[:id])
		users_list_ids = current_user.lists.pluck(:id)
		@playlist.user_bookmarks.each do |ub|
			other_playlists_with_url = UserBookmark.find_all_by_bookmark_url_id(ub.bookmark_url_id).pluck(:playlist_id)
			if (users_list_ids & other_playlists_with_url).empty?	#later, I should write a function that aborts as soon as a match is found
				current_user.default_list.user_bookmarks << ub;
			else
				ub.delete
			end
		end
		@playlist.delete
	end

	def destroy_with_contents
		@playlist = current_user.lists.find(params[:id])
		@playlist.user_bookmarks.each {|ub| ub.delete }
		@playlist.delete
	end

	private
		def authorize_owner
			if(current_user.nil?)
				redirect_to login_path, :notice => "You have to be logged in as the owner of that playlist to access this funcationality."
			end
			playlist = current_user.playlists.find_by_id(params[:id])
			if (playlist.nil?)
				redirect_to current_user, :notice => "You have to be logged in as the owner of that playlist to access this funcationality."
			end
		end

		def authorize
			if(current_user.nil?)
				redirect_to login_path, :notice => "You have to log in to make a playlist."
			end
		end

		def authorize_show_playlist
			if !(Playlist.find(params[:id]).public)
				if(current_user.nil?)
					redirect_to login_path, :notice => "You have to be logged in as the owner of that playlist to see it."
				end
				playlist = current_user.playlists.find_by_id(params[:id])
				if (playlist.nil?)
					redirect_to current_user, :notice => "You have to be logged in as the owner of that playlist to see it."
				end
			end
		end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_playlist_form.html.erb
<%= form_for @playlist do |f| %>
  <% if @playlist.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @playlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :playlist_name %><br />
    <%= f.text_field :playlist_name %>
  </div>
  <div class="actions"><%= f.submit "Create Playlist" %></div>
<% end %>

<p>
<%= link_to 'Playlist Index', playlists_path%>
</p>

app/views/playlists/edit.html.erb
<div class="row-fluid">
<%= render '/layouts/sidebar' %>
<div class="span9">
  <h1>Edit Playlist</h1>
  <%= render 'playlist_form' %>
</div>
</div>

app/views/playlists/index.html.erb
<div class="row-fluid">
	<%= render '/layouts/sidebar' %>
	<div class="span5">
	<h1>Playlist index</h1><br />
		<div class="row-fluid">
			<div class="span5" %>
				<% @lists.each do |pl| %>
					<div class="playlist_links">
						<%= link_to pl.playlist_name, pl %>
					</div>
				<% end %>
			<br /><br />
			<%= link_to 'Create New Playlist', new_playlist_path %>
		</div>
		<div class="span7"%>
			<% @lists.each do |pl| %>
				<div class="playlist_links">
				  <%= link_to "<i class='icon-edit'></i> edit".html_safe, edit_playlist_path(pl), class: "btn btn-small btn-info"%>
				  <%= link_to "<i class='icon-trash'></i> delete".html_safe, playlist_path(pl), class: "remove_playlist btn btn-small btn-danger", :remote => true, :method => :delete, :confirm => "This deletes the playlist and puts the otherwise un-playlisted videos on your home page" %>
				  
				</div>
			<% end %>
		</div>
	</div>
	</div></div>

app/views/playlists/new.html.erb
<div class="row-fluid">
	<%= render '/layouts/sidebar' %>
<div class="span9">
  <h1>New Playlist</h1>
  <%= render 'playlist_form' %>
</div>
</div>

app/views/playlists/show.html.erb
<div class="row-fluid">
  <%= render '/layouts/sidebar' %>
<div class="span5" id="bookmark_list_view">
  <h2><%= @playlist.playlist_name %></h2>
  <% if current_user %>
  <%= link_to 'Add A Link <i class="icon-plus icon-white"></i>'.html_safe, '', class:"btn btn-primary new-bookmark-modal-link" %>
    <div id="new-bookmark-modal-holder">
        <%= render '/user_bookmarks/modal_new' %>
    </div>
  <% end %>
  <br />
  <div class="input-prepend">
    <span class="add-on"><i class="icon-filter"></i></span>
    <%= search_field_tag 'filter_uncategorized', '', :placeholder=>"Filter Bookmarks" , "data-toggle"=>"tooltip", "data-trigger"=>"manual", "data-title"=>"here", "data-placement"=>"bottom"%>
  </div>
  <div class="bookmark-list">
    <% @playlist.user_bookmarks.each_with_index do |user_bookmark,i| %>
      <% if i > 0 and !user_bookmark.id.nil? %>
        <hr>
      <% end %>
      <% if user_bookmark.id %>
        <%= render :partial =>'/user_bookmarks/bookmark_fields.html.erb', :locals => {:user_bookmark => user_bookmark} %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="span4">
  <div id="detail_bookmark_view_container">
    <div id="detail_bookmark_view">
    </div>
  </div>
</div>
</div>