config/routes.rb
BookmarkSite::Application.routes.draw do

  match 'usernotfound' => 'static_pages#usernotfound', as: 'usernotfound'

  resources :sessions, :only => [:create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => "static_pages#welcome"

  get "jsfiles/bookmarklet(.:format)" => "jsfiles#bookmarklet", :as => :bookmarklet
  get "jsfiles/jquery_bookmarklet.min(.:format)" => "jsfiles#jquery_bookmarklet", :as => :bookmarklet_setup
  get "jsfiles/cleanslate(.:format)" => "jsfiles#cleanslate", :as => :cleanslate
  get "jsfiles/playground(.:format)" => "jsfiles#playground", :as => :playground
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#process_bookmarklet', :via => :post
  match 'jsfiles/process_bookmarklet(.:format)' => 'jsfiles#preflight', :via => :options

  match 'playlists/:playlist_id/user_bookmarks/:id/move(.:format)' => 'user_bookmarks#move', :via => :post

  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'info', to: 'static_pages#info', as: 'info'
  get 'privacy', to: 'static_pages#privacy', as: 'privacy'
  get 'contact', to: 'static_pages#contact', as: 'contact'

  resources :playlists do
    resources :user_bookmarks
  end

  resources :bookmark_urls, :only => [:create]

  match 'users/temp(.:format)' => 'users#temp', :as => :temp_users, :via => :get
  match 'users/create_temp(.:format)' => 'users#create_temp', :as => :create_temp_users, :via => :get

  resources :users do
    member do
      get 'upgrade'
      put 'process_upgrade'
    end
  end

  match '/:username' => 'users#show'

end

app/views/layouts/_footer.html.erb
<div class="footer"><div class="footer-spacer"></div><p>© 2013 VRepo</p></div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "VRepo".html_safe, welcome_path, class:"logo", style:"color:#3880FF" %></li>
          <li><%= link_to "<img src='/assets/glyphicons/glyphicons_021_snowflake.png'></img> About Us".html_safe, about_path %></li>
          <li><%= link_to "<img src='/assets/glyphicons/glyphicons_195_circle_info.png'></img> Info".html_safe, info_path %></li>
          <li data-toggle="tooltip" data-trigger="manual" data-placement="bottom" id="bookmark_bar" title="Bookmark Bar: (If there's no bookmark bar under the address bar, you can probably enable it)" style="position:fixed; left:25%;"></li>
          <li><%= link_to "<img src='/assets/glyphicons/glyphicons_203_lock.png'></img> Privacy".html_safe, privacy_path %></li>
          <li><%= link_to "<img src='/assets/glyphicons/glyphicons_010_envelope.png'></img> Contact".html_safe, contact_path %></li>
          <li><%= link_to "<img src='/assets/glyphicons/glyphicons_029_notes_2.png'></img> Blog".html_safe, 'http://vrepo.wordpress.com/'%></li>
        </ul>
          <% if current_page?(current_user) or current_page?(username_path(current_user))%>
            <div style="position:absolute; left:47%; top:29px; background:#1b1b1b; height:14px">
              <a class="btn btn-mini btn-inverse info-pane-button">Expand <i class="icon-chevron-down"></i></a>
            </div>
          <% end %>
        <ul class="nav pull-right">
        	<% if current_user.nil? %>
          	<!-- <li><a href="#">1 Click Save</a></li> -->
            <%= form_tag sessions_path, class:"navbar-form pull-left" do %>
              <%= text_field_tag :username, '', :placeholder => 'Username' ,id:"navbar-input-1"%>
              <%= password_field_tag :password,'', :placeholder=>'Password' ,id:"navbar-input-2"%>
              <button type="submit" class="btn btn-small" id="navbar-form-button">Sign in</button>
            <% end %>
            <li class="divider-vertical"></li>
            <li><a href="/signup">Sign Up</a></li>
             <!--<li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                <%#= form_tag sessions_path do %>
							    <%#= text_field_tag :username, params[:username], :placeholder => 'Username' %>
							    <%#= password_field_tag :password,'', :placeholder=>'Password' %>
                  <button type="submit" class="btn">Sign in</button>
								<%# end %>
              </div>
            </li> -->
          <% else %>
            <div class="navbar-form pull-left"><a class="btn btn-inverse" id="login-btn"><i class="icon-white icon-heart"></i> Returning Users</a></div>
            <!-- <div style="display:none;" id="nav-login"> -->
              <%= form_tag sessions_path, class:"navbar-form pull-left", style:"display:none", id:"nav-login" do %>
                <%= text_field_tag :username, '', :placeholder => 'Username' ,id:"navbar-input-1"%>
                <%= password_field_tag :password,'', :placeholder=>'Password' ,id:"navbar-input-2"%>
                <button type="submit" class="btn btn-small" id="navbar-form-button">Sign in</button>
              <% end %>
            <!-- </div> -->
            <li class="divider-vertical"></li>
            <% if current_user.human or !current_page?(:controller => 'static_pages', :action=>'welcome') %>
              <li class="dropdown">
            <% else %>
              <li class="dropdown" id="temp-acct-popover-holder" data-html=true data-toggle="popover" data-placement="bottom" data-trigger="manual" data-content="<div id=temp-acct-popover>An account has been created for you.<hr>The password is the same as the username. <hr>Since this is a temp. account, your account gets wiped when you leave unless you confirm you're human.</div>">
            <% end %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src='/assets/glyphicons/glyphicons_003_user.png'> </img><%= current_user.username %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
	            	<li><%=link_to "Home", current_user , "tabindex" => "-1"%></li>
								<li><%=link_to "User Settings", edit_user_path(current_user), "tabindex" => "-1"%></li>
                <li class="divider"></li>
								<li><%= link_to 'Log Out', logout_path , "tabindex" => "-1"%></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_info_pane.html.erb
<div class = "row-fluid" id="info-pane" style="display:none">
  <div class="span3">
    <!-- INFO LEFT BEGIN-->
    <div class = "info_box" >
      <h4>Using the Bookmarklet</h4>
      Drag the <a class="indicator_tooltip" data-tooltip-selector="#bookmarklet">bookmarklet</a> to the <a class="indicator_tooltip" data-tooltip-selector="#bookmark_bar">bookmark bar</a>.
      <div data-swf="http://releases.flowplayer.org/5.3.2/flowplayer.swf" class="flowplayer color-light no-toggle is-poster" data-ratio="0.5">
        <video>
           <source type="video/webm" src="/assets/bookmarklet_recording.webm"/>
           <source type="video/mp4" src="/assets/bookmarklet_recording.mp4"/>
           <source type="video/ogv" src="/assets/bookmarklet_recording.ogv"/>
        </video>
       </div>
    </div>
    <!-- INFO LEFT END -->
  </div>
  <div class="span5">
    <!-- INFO MIDDLE BEGIN-->
    <div class="info_box">
      <h3 style="margin-bottom:8px;margin-top:8px;">Welcome to<span class="logo"> VRepo!</span></h3>
      <h5 style="text-align:center;margin-top:6px;">A Utility for Anonymously Bookmarking Adult Content</h5>
      <p>This is your homepage, <a href="#"><i>www.vrepo.com/<%=@user.username%></i></a>, which you can access anytime without having to login. You can require logging-in from User Settings.</p>
    </div>
    <!-- INFO MIDDLE END -->
  </div>
  <div class="span2">
    <!-- INFO RIGHT BEGIN-->
    <div class = "info_box" >
      <h4>Instant Account</h4>
      <p>The dropdown menu has links to:</p>
      <ul>
        <li>User Home [here]</li>
        <li>User Settings</li>
        <li>Log out</li>
      </ul>
    </div>
  </div>
  <div class="span2" style="margin-left:2%">
    <div class = "info_box" >
      <h4>User Settings</h4>
      <p>Edit your:</p>
      <ul>
        <li>Username</li>
        <li>Password <br/>[blank by default]</li>
        <li>Access Settings</li>
      </ul>
    </div>
  </div>
      <!-- INFO RIGHT END -->
</div>
<span style="position:relative; left:47%; top:15px; display:none;">
  <% if flash[:instant_account] %>
    <span style="display:none" id="introduction"></span>
  <% end %>
  <a class="btn btn-mini btn-inverse info-pane-button">Collapse <i class="icon-chevron-up"></i></a>
</span>
<hr style="height: 12px;border: 0;border-top: medium double #777; color: #333;margin:5px 0 0 0px; display:none">

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) and name != :login_error %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="span3">
    <div class="well sidebar-nav hasBookmarklet">

            <div class="sidebar-title">Bookmarklet</div>
      <ul class="nav nav-list">
        <% if current_user %>
            <li><a id="bookmarklet" title="vrepo bookmarklet" data-toggle="tooltip" data-trigger="manual"data-title="here" href ="javascript:(function(){jq=document.createElement('SCRIPT');jq.type='text/javascript';jq.src='//www.vrepo.com/jsfiles/jquery_bookmarklet.min.js';document.getElementsByTagName('head')[0].appendChild(jq);})();"><%= image_tag '/assets/glyphicons/glyphicons_072_bookmark.png', alt:"vrepo bookmarklet" %> Drag to your bookmark bar</a><li>
            </ul></div>
            <div class="well sidebar-nav">
                <div class="sidebar-title">Actions</div>
                <ul class="nav nav-list">
            <li <%= "class=active" if current_page?(username_path(current_user)) %> > <%= link_to "<i class='icon-home'></i> Home".html_safe, username_path(current_user) %></li>
            <!-- if there is a valid playlist
            make sure that the current_user owns this playlist, 
            that this is the show playlist view
            and that the playlist isnt' the default one
            -->
            <% if @playlist and @playlist.id %>
                <% if (@playlist.user == current_user) %>
                    <li><%= link_to "<i class='icon-plus'></i> Add a Bookmark".html_safe, new_playlist_user_bookmark_path(current_user.default_list), :class => "new-bookmark-modal-link" , "data-toggle"=>"tooltip", "data-trigger"=>"manual", "data-title"=>"here", "data-placement"=>"top" %></li>
                    <% if current_page?(@playlist) and @playlist != current_user.default_list %>
                        <li><%= link_to ("<i class='icon-plus'></i>  Add a Bookmark to "+@playlist.playlist_name).html_safe, new_playlist_user_bookmark_path(@playlist), :class => "new-bookmark-modal-link"%></li>
                    <% end %>
                <% end %>
            <% end %>
            <li <%= "class=active" if current_page?(new_playlist_path) %> ><%= link_to "<img src='/assets/new_playlist_icon.png'></img> Create New Playlist".html_safe, new_playlist_path%></li>
            <li class="nav-header">My Playlists</li>
            <li <%= "class=active" if current_page?(playlists_path) %> ><%= link_to "<i class='icon-list'></i> Index of All My Playlists".html_safe, playlists_path%></li>
            <% if !(current_user.lists.empty?) and (current_user.lists.first.id?) %>
                <% current_user.lists.each do |pl|%>
                    <% if pl.id %>
                        <% if pl == @playlist %>
                            <li class="active"><%=link_to(("<i class='icon-folder-open'></i> "+ pl.playlist_name).html_safe, pl )%></li>
                        <% else %>
                            <li><%=link_to(("<i class='icon-folder-close'></i> "+pl.playlist_name).html_safe, pl )%></li>
                        <% end %>
                    <% end %>
                <% end %>
            <% else %>
                <li style="font-size:12px">You don't have any playlists yet</li>
            <% end %>
        <% else %>
            <li class="nav-header">Actions</li> 
            <li><strong><%= link_to "Sign Up", signup_path  %></strong></li>
        <% end %> 
      </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VRepo" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" type="text/css" href="http://releases.flowplayer.org/5.3.2/skin/minimalist.css" />
    <%= javascript_include_tag "application" %>
    <script src="http://releases.flowplayer.org/5.3.2/flowplayer.min.js"></script>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render '/layouts/header' %>
    <div class="container-fluid">
      <!-- <div class="row-fluid"> -->
        <%#= render '/layouts/messages' %>

        <%= yield %>
      <!-- </div> -->
    </div> <!-- end of .container -->
    <div id="modalHolder">
    </div>
    <%= render '/layouts/footer' %>
  </body>
</html>